### ISSUE TITLE
Cannot unassigne user without replace them with someone else.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax-poland/adaptarr-front#154]
While creating and managing process should be possible to discharge user and leave sloth empty.

**Comment by PiotrKozlowski** [comment]
@aiwenar There is no way to remove user from slot - we can also assign someone else

**Comment by paulinaszczucinska** [comment]
I agree with @aiwenar (who left his comment on slack) that the option to leave a slot empty might be useful.
