### ISSUE TITLE
Need to change wording.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax-poland/adaptarr-front#155]
![Screenshot from 2019-09-03 17-16-38](https://user-images.githubusercontent.com/47241114/64186143-a155f400-ce6e-11e9-8a3f-33a589430d75.png)

**Comment by PiotrKozlowski** [comment]
@MartaSztuka What should be done here?

**Comment by MartaSztuka** [comment]
Suggestions:
Zostałeś/aś usunięty/a (...) >> Twoja funkcja została przekazana innemu użytkownikowi (...)
Zostałeś/aś przypisany/a (...) >> Przypisano Cię (...)
