### ISSUE TITLE
Allow editing users' team permissions which are not depending on role

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-front#180]
User with `team:manage` or `member:edit-permissions` on `Teams and roles` screen in team members tab should be able to click on user and edit his permission which are separate of user's role permissions.

**Comment by MartaSztuka** [comment]
User's team permissions can be changed independently of roles.
![Screenshot from 2019-10-08 13-39-45](https://user-images.githubusercontent.com/47241114/66392879-5ed58900-e9d1-11e9-91d1-030e9694d823.png)
