### ISSUE TITLE
Allow highlighting text with some message

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-front#193]
Allow adding highlights to the text in editor with some additional message.

This should be temporary plugin until we implement comments.

**Comment by MartaSztuka** [comment]
Highlighting can be added and deleted, colours match, comments works. It's all good.
![Screenshot from 2019-10-21 10-05-38](https://user-images.githubusercontent.com/47241114/67187380-5d04c000-f3ea-11e9-915a-6db5cfb6c19a.png)
