### ISSUE TITLE
Allow clearing local indexedDB for specific modules

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-front#209]
Sometimes user may want to remove his local changes from indexedDB, but currently it has to be done by asking me or @aiwenar to create custom file which then should be imported in Helpdesk screen > import db. ex: https://katalysteducation.slack.com/archives/GCSUE8C01/p1572877631002600

User should be able to open some kind of list of drafts, select those for which he would like to remove locally saved data and just click <kbd>Delete</kbd>.

cc. @PatBoj @paulinaszczucinska

**Comment by aiwenar** [comment]
This is already implemented:

```js
await PersistDB.load(documentId).then(db => db.discard())
```

We just need to create a UI for it.
