### ISSUE TITLE
Regression tests 12-11-19

### ISSUE THREAD

**Issue by MartaSztuka** [openstax-poland/adaptarr-front#224]
- [x]  Books > Remove madule > Are you sure? (Cancel Delete) Delete should be replaced with Remove
- [x]  Increase distance between buttons and other elements, so they don't touch. ![Screenshot from 2019-11-13 11-33-16](https://user-images.githubusercontent.com/47241114/68763233-3e27d100-0618-11ea-8bf0-6e317cdc6e9a.png)
- [ ]  **Bug:** Dates in helpdesk chat acting weird. ![Screenshot from 2019-11-13 13-12-45](https://user-images.githubusercontent.com/47241114/68763311-69aabb80-0618-11ea-9805-5f4fe66a8784.png)
- [ ]  **Feature:** both panels on each window can be rolled up (like menu bar). It would be useful to close one panel when you don't need it, for example `Free slots`. Also elements won't be clustered on one side of the screen with other half empty.  ![Screenshot from 2019-11-13 11-43-28](https://user-images.githubusercontent.com/47241114/68763609-269d1800-0619-11ea-80be-01a1bbc7f13d.png)
- [x]  Lables box should be bigger, so all elements fit and aren't soo compressed. Also `edit` and `label name` icons should be aligned.
![Screenshot from 2019-11-13 12-28-55](https://user-images.githubusercontent.com/47241114/68763754-83003780-0619-11ea-8f4b-511810aef8d1.png)
- [ ] **Feature:** On dashboard we can add 'padlock'. When user needs to import/export CNXML file can 'unlock it' and get access to it, but 'Details' button isn't permanently next to each module. Labels can temporary stay under 'flower'.
- [ ]  Chat message gets bold/italic with ctrl+B/I when continue writing tex should get back to 'normal'
![Screenshot from 2019-11-13 15-34-36](https://user-images.githubusercontent.com/47241114/68773874-9668ce00-062c-11ea-8ab8-6e1619c7a285.png)

**Comment by PiotrKozlowski** [comment]
> Bug: Dates in helpdesk chat acting weird. 

I've created separate issue for this: https://github.com/openstax-poland/adaptarr-server/issues/47

> Feature: both panels on each window can be rolled up (like menu bar) 

Can you add more details on what's expected result for this?

> Feature: On dashboard we can add 'padlock'. When user needs to import/export CNXML file can 'unlock it' and get access to it, but 'Details' button isn't permanently next to each module. Labels can temporary stay under 'flower'.

Idea of padlock was introduced for process managers / admins to hide unnecessary UI for removing / changing items like books or modules.
<kbd>Details</kbd> however was created with intent to be more often or equally used by users which wants to edit drafts. Currently it may be not the case, but we will be adding more features to this screen in the future, so I will vote for not chanign this :D

**Comment by PiotrKozlowski** [comment]
> Lables box should be bigger, so all elements fit and aren't soo compressed. Also edit and label name icons should be aligned.

@MartaSztuka Will this be okay or you want even more changes?
Before:
![obraz](https://user-images.githubusercontent.com/31478212/68781776-8eaf2680-0638-11ea-99f8-55cb88c8efc3.png)

After:
![obraz](https://user-images.githubusercontent.com/31478212/68781653-63c4d280-0638-11ea-9167-65aa5dab7893.png)

**Comment by MartaSztuka** [comment]
@PiotrKozlowski Looks way better, but corners could be lass rounded ;)

**Comment by PiotrKozlowski** [comment]
> It would be useful to close one panel when you don't need it, for example Free slots

But then how to open it?

>  Looks way better, but corners could be less rounded ;)

Is this okay?
![obraz](https://user-images.githubusercontent.com/31478212/68782641-0762b280-063a-11ea-8454-f52621e4b442.png)

**Comment by MartaSztuka** [comment]
Labels window looks good, about the panel we close, can be opened just like menu, clicking on icon or whatnot, I'm thinking about something similar to browser tabs.

**Comment by PiotrKozlowski** [comment]
Could you show me this on sample screenshot?

**Comment by MartaSztuka** [comment]
Something along this, but maybe `Free sloths` can be replaced with icon, so titles won't be visible.
![Screenshot from 2019-11-14 09-56-57](https://user-images.githubusercontent.com/47241114/68841670-4ee25080-06c5-11ea-8c98-3816208a614c.png)

**Comment by PiotrKozlowski** [comment]
> Chat message gets bold/italic with ctrl+B/I when continue writing tex should get back to 'normal'

This require us to update slate so it will not be fixed before Gemini release. I've created separate issues for this in current sprint: https://github.com/openstax-poland/adaptarr-front/issues/229
Update will also fix this issue: https://github.com/openstax-poland/adaptarr-front/issues/42

**Comment by PiotrKozlowski** [comment]
> Bug: Dates in helpdesk chat acting weird. 

@MartaSztuka fix for this will be on staging at monday 25th

**Comment by PiotrKozlowski** [comment]
@MartaSztuka 

> Bug: Dates in helpdesk chat acting weird. 

Should be already fixed

> Chat message gets bold/italic with ctrl+B/I when continue writing tex should get back to 'normal'

Please create separate card for this and link it to: https://github.com/openstax-poland/adaptarr-front/issues/229

> Feature: both panels on each window can be rolled up (like menu bar). It would be useful to close one panel when you don't need it, for example Free slots. Also elements won't be clustered on one side of the screen with other half empty. 

and

> Feature: On dashboard we can add 'padlock'. When user needs to import/export CNXML file can 'unlock it' and get access to it, but 'Details' button isn't permanently next to each module. Labels can temporary stay under 'flower'.

I think we've decided to collaps free slots and change buttons design for drafts instead of this.

 If this is correct then we could close this issue :)
