### ISSUE TITLE
Change how insert buttons are presented

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-front#235]
### Discussion
Currentlly insert buttons are large and they take a lot of space.
My proposal is to remove title from under icons and display it conditionally when user hover the button.
We should probably also order somehow buttons to be more intuitive (ask ppl which are already working in Adaptarr?)

### Current design for insert tools
![obraz](https://user-images.githubusercontent.com/31478212/69343084-3053fa80-0c6d-11ea-90b0-6e385a806483.png)

### How it could look:
![obraz](https://user-images.githubusercontent.com/31478212/69343030-131f2c00-0c6d-11ea-893e-2909b56b1628.png)

**Comment by paulinaszczucinska** [comment]
Okay. It is a great idea.
