### ISSUE TITLE
Problems with pasting text into table tiltes and alt texts

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-front#269]
When pasting text into figure alt text or table title editor is sometimes breaking. This may happen also in other elements.

This is probably because when we copy text it is slate fragment rather than a string.

The solution, for now, could be adding Plugin which will detect if a user wants to paste the text into an element that can possibly break and transform the copied text into a string.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-01-30 10-53-06](https://user-images.githubusercontent.com/47241114/73439082-5d004e80-434f-11ea-8755-7bbfa1994491.png)
![Screenshot from 2020-01-30 10-57-08](https://user-images.githubusercontent.com/47241114/73439090-5eca1200-434f-11ea-8e48-b89eec7839c5.png)
![Screenshot from 2020-01-30 10-57-19](https://user-images.githubusercontent.com/47241114/73439097-5ffb3f00-434f-11ea-8bcb-50abdde57c28.png)
