### ISSUE TITLE
Highlight on proposed changes.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax-poland/adaptarr-front#278]
1. User propose change in text.
![Screenshot from 2020-01-22 14-43-14](https://user-images.githubusercontent.com/47241114/72899144-b3ed9e80-3d25-11ea-8342-139fea263e47.png)
2. User mark deleted word with highlight.
![Screenshot from 2020-01-22 14-43-25](https://user-images.githubusercontent.com/47241114/72899151-b5b76200-3d25-11ea-82de-1ceba0f9da90.png)
3. When user click ok highlight icon again with coursor on marked text. Both highlight and red colour dissapear. Same with 'green text'. ![Screenshot from 2020-01-22 14-43-42](https://user-images.githubusercontent.com/47241114/72899155-b7812580-3d25-11ea-9d8f-b44c4cea4333.png)

Both highlight and red/green colour letter should be visible.
I happens when user has `Propose changes' and 'Accept changes' permission on current step.

**Comment by PiotrKozlowski** [comment]
Currently, the highlight is behaving the same as the term, code or any other inline element which means that selected text is wrapped in suggestion_remove and highlight is added as suggestion_insert.

We would like to have normal support for highlights.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-01-30 11-20-14](https://user-images.githubusercontent.com/47241114/73441046-a900c280-4352-11ea-987f-45b143552c95.png)
